### PR TITLE
Fix prosody syntax error

### PR DESCRIPTION
**Pull request by wichert**
Using an explicit `+` in the prosody rate, for example `<prosody rate="+15%">` results in this error:

```json
{
   "code_description": "Bad Request", 
   "code": 400, 
   "error": "Tag <prosody> has invalid attribute rate= 10%"
}
```

### CODE REVIEW

**Comment by nfriedly** [comment]
I don't think that `+` is disallowed, I think something in the stack was converting that into a space (which is disallowed).

I think the SDK should probably catch these and urlencode them.

**Comment by nfriedly** [comment]
Actually, the SDK does do this, but the demo isn't using the SDK...

**Comment by ehdsouza** [comment]
Fixed in https://github.com/watson-developer-cloud/text-to-speech-nodejs/pull/81

**Comment by ehdsouza** [comment]
@wichert Thanks for the Pull Request. I fixed the encoding issue and did some other updates in #81

**Pull request closed without merging**
